In [3]:
token = 'token'
from datasets import load_dataset

# Use streaming mode to avoid memory issues
dataset = load_dataset(
    "oscar-corpus/OSCAR-2201",
    language="hi",
    split="train",
    token = token,
    streaming=True,  # This avoids loading everything into memory
)



README.md:   0%|          | 0.00/31.5k [00:00<?, ?B/s]

OSCAR-2201.py:   0%|          | 0.00/19.9k [00:00<?, ?B/s]

The repository for oscar-corpus/OSCAR-2201 contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/oscar-corpus/OSCAR-2201.
You can avoid this prompt in future by passing the argument `trust_remote_code=True`.

Do you wish to run the custom code? [y/N] y


In [2]:
# Print just the first 10 samples
for i, sample in enumerate(dataset):
    print(sample)
    if i >= 4:
        break

{'id': 0, 'text': 'हांसी- हांसी देह व्यापार का भंडाफोड़ हुआ है। थाना शहर पुलिस ने तीन महिलाओं व एक पीजी संचालक को अनैतिक कार्य करने के आरोप में गिरफ्तार कर लिया है। पुलिस को शहर के जींद बाइपास पर स्थित पीसी स्टार पीजी पर देह व्यापार की गुप्त सूचना मिली थी। पुलिस ने एक बोगस ग्राहक तैयार कर उसे पीजी में भेजा। जैसे ही सौदा तय हुआ।\nपुलिस की सूचना सही पाई गई और तुरंत पुलिस ने वहां से तीन महिलाओं और पीजी संचालक को गिरफ्तार कर लिया। गिरफ्तार की गई महिलाओं में एक महिला हिमाचल प्रदेश की है, जबकि दो हरियाणा की हैं। गिरप\u200dतार लोगों के खिलाफ विभिन्न धाराओं में कार्रवाई की जा रही है।', 'meta': {'warc_headers': {'warc-record-id': '<urn:uuid:b035389a-2c88-43f8-a9d3-9f7576d3194a>', 'warc-date': '2021-12-09T05:04:19Z', 'content-type': 'text/plain', 'content-length': 1443, 'warc-type': 'conversion', 'warc-identified-content-language': 'hin,eng', 'warc-refers-to': '<urn:uuid:3e1442f1-feba-41ba-aff9-af258edee943>', 'warc-target-uri': 'http://www.indiakidahad.com/2020/09/14/%E0%A4%B9%E0%A4%BE%E0%A4%82

In [4]:
n_samples = 50
output_file = "oscar_hi_sample.txt"

with open(output_file, "w", encoding="utf-8") as f:
    for i, example in enumerate(dataset):
        text = example.get("text", "").strip()
        if text:
            f.write(text + "\n\n")  # two newlines for separation
        if i + 1 >= n_samples:
            break

print(f"Saved {n_samples} samples to {output_file}")


Saved 50 samples to oscar_hi_sample.txt


In [5]:
# Read the sampled text
with open("oscar_hi_sample.txt", "r", encoding="utf-8") as f:
    text = f.read()

# Total number of characters
vocab_size = len(text)

# Unique characters
unique_chars = set(text)
num_unique_chars = len(unique_chars)

# Print results
print(f"Total characters in dataset: {vocab_size}")
print(f"Number of unique characters: {num_unique_chars}")
print(f"Unique characters: {sorted(unique_chars)}")


Total characters in dataset: 244859
Number of unique characters: 311
Unique characters: ['\t', '\n', ' ', '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '=', '>', '?', '@', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', '\\', ']', '^', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '{', '|', '}', '~', '©', '«', '®', '»', '×', 'ç', 'ñ', 'Δ', 'а', 'в', 'д', 'е', 'ж', 'з', 'и', 'й', 'к', 'л', 'м', 'н', 'о', 'п', 'р', 'с', 'т', 'ь', 'я', 'ا', 'د', 'ر', 'س', 'ف', 'و', 'ی', 'ँ', 'ं', 'ः', 'अ', 'आ', 'इ', 'ई', 'उ', 'ऊ', 'ऋ', 'ऍ', 'ऎ', 'ए', 'ऐ', 'ऑ', 'ओ', 'औ', 'क', 'ख', 'ग', 'घ', 'च', 'छ', 'ज', 'झ', 'ञ', 'ट', 'ठ', 'ड', 'ढ', 'ण', 'त', 'थ', 'द', 'ध', 'न', 'ऩ', 'प', 'फ', 'ब', 'भ', 'म', 'य', 'र', 'ऱ', 'ल', 'व', 'श', 'ष', 'स', 'ह'

In [6]:
import re
# Path to input and output files
input_file = "oscar_hi_sample.txt"
output_file = "oscar_hi_cleaned.txt"

# Devanagari Unicode range: U+0900 to U+097F
# Optional: Add some punctuation if needed (like । or whitespace)
devanagari_pattern = re.compile(r'^[\u0900-\u097F]+$')
def is_hindi_word(word):
    return devanagari_pattern.match(word) is not None

cleaned_lines = []

with open(input_file, "r", encoding="utf-8") as infile:
    for line in infile:
        words = line.strip().split()
        hindi_words = [word for word in words if is_hindi_word(word)]
        if hindi_words:
            cleaned_lines.append(" ".join(hindi_words))

# Save cleaned lines to a new file
with open(output_file, "w", encoding="utf-8") as outfile:
    for line in cleaned_lines:
        outfile.write(line + "\n")

print(f"Cleaned Hindi text saved to {output_file}")


Cleaned Hindi text saved to oscar_hi_cleaned.txt


In [7]:
# Read the cleaned text
with open("oscar_hi_cleaned.txt", "r", encoding="utf-8") as f:
    text = f.read()

# Total number of characters
vocab_size = len(text)

# Unique characters
chars = sorted(list(set(text)))
num_unique_chars = len(chars)

# Print results
print(f"Total characters in dataset: {vocab_size}")
print(f"Number of unique characters: {num_unique_chars}")
print(''.join(chars))

Total characters in dataset: 178699
Number of unique characters: 84

 ँंःअआइईउऊऋऍऎएऐऑओऔकखगघचछजझञटठडढणतथदधनऩपफबभमयरऱलवशषसह़ािीुूृॅेैॉोौ्ख़ग़ज़ड़ढ़फ़य़ॠ।०१२४५७८॰


In [8]:
sample_size = 5  # number of lines to print

with open("oscar_hi_cleaned.txt", "r", encoding="utf-8") as f:
    for line in f:
        print(line)
        if sample_size<=0:
            break
        sample_size-=1


हांसी देह व्यापार का भंडाफोड़ हुआ है। थाना शहर पुलिस ने तीन महिलाओं व एक पीजी संचालक को अनैतिक कार्य करने के आरोप में गिरफ्तार कर लिया है। पुलिस को शहर के जींद बाइपास पर स्थित पीसी स्टार पीजी पर देह व्यापार की गुप्त सूचना मिली थी। पुलिस ने एक बोगस ग्राहक तैयार कर उसे पीजी में भेजा। जैसे ही सौदा तय हुआ।

पुलिस की सूचना सही पाई गई और तुरंत पुलिस ने वहां से तीन महिलाओं और पीजी संचालक को गिरफ्तार कर लिया। गिरफ्तार की गई महिलाओं में एक महिला हिमाचल प्रदेश की जबकि दो हरियाणा की हैं। लोगों के खिलाफ विभिन्न धाराओं में कार्रवाई की जा रही है।

ये सब अफवाह कल मैंने प्रधानमंत्री से मुलाकात की और हमने राज्य के विकास पर विस्तृत रूप से चर्चा की। अगले महीने के पहले हफ़्ते में मैं फिर दिल्ली इस्तीफा देने के सवाल पर कर्नाटक के मुख्यमंत्री येदियुरप्पा

तलोजा जेल में बंद मुंबई पुलिस के निलंबित अधिकारी सचिन वाजे ने विशेष अदालत में जमानत याचिका दायर की और अदालत से उन्हें जमानत पर रिहा करने का अनुरोध किया है क्योंकि उनकी गिरफ़्तारी के दिनों के भीतर चार्जशीट दाखिल नहीं कर पाई है।

देश में पिछले घंटे में कोरोन

In [9]:
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

print(encode("पुलिस की सूचना"))
print(decode(encode("पुलिस की सूचना")))

[39, 57, 47, 55, 51, 1, 19, 56, 1, 51, 58, 23, 37, 54]
पुलिस की सूचना


In [9]:
# now we encoded the entire text dataset and stored it into a torch.Tensor
import torch # we use PyTorch: https://pytorch.org
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) # the 1000 characters we looked at earier will to the GPT look like this

torch.Size([178699]) torch.int64
tensor([52, 54,  3, 51, 56,  1, 35, 61, 52,  1, 48, 66, 44, 54, 39, 54, 45,  1,
        19, 54,  1, 42,  3, 30, 54, 40, 64, 30, 53,  1, 52, 57,  6,  1, 52, 62,
        75,  1, 34, 54, 37, 54,  1, 49, 52, 45,  1, 39, 57, 47, 55, 51,  1, 37,
        61,  1, 33, 56, 37,  1, 43, 52, 55, 47, 54, 17,  3,  1, 48,  1, 14, 19,
         1, 39, 56, 25, 56,  1, 51,  3, 23, 54, 47, 19,  1, 19, 64,  1,  5, 37,
        62, 33, 55, 19,  1, 19, 54, 45, 66, 44,  1, 19, 45, 37, 61,  1, 19, 61,
         1,  6, 45, 64, 39,  1, 43, 61,  3,  1, 21, 55, 45, 40, 66, 33, 54, 45,
         1, 19, 45,  1, 47, 55, 44, 54,  1, 52, 62, 75,  1, 39, 57, 47, 55, 51,
         1, 19, 64,  1, 49, 52, 45,  1, 19, 61,  1, 25, 56,  3, 35,  1, 41, 54,
         7, 39, 54, 51,  1, 39, 45,  1, 51, 66, 34, 55, 33,  1, 39, 56, 51, 56,
         1, 51, 66, 28, 54, 45,  1, 39, 56, 25, 56,  1, 39, 45,  1, 35, 61, 52,
         1, 48, 66, 44, 54, 39, 54, 45,  1, 19, 56,  1, 21, 57, 39, 66, 33,  1,
       

In [10]:
# Let's now split up the data into train and validation sets
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

In [11]:
block_size = 8
train_data[:block_size+1]

tensor([52, 54,  3, 51, 56,  1, 35, 61, 52])

In [12]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([52]) the target: 54
when input is tensor([52, 54]) the target: 3
when input is tensor([52, 54,  3]) the target: 51
when input is tensor([52, 54,  3, 51]) the target: 56
when input is tensor([52, 54,  3, 51, 56]) the target: 1
when input is tensor([52, 54,  3, 51, 56,  1]) the target: 35
when input is tensor([52, 54,  3, 51, 56,  1, 35]) the target: 61
when input is tensor([52, 54,  3, 51, 56,  1, 35, 61]) the target: 52


In [13]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[54, 35, 19,  1, 37, 61,  1, 19],
        [54,  1, 43, 61, 45, 56,  0, 48],
        [45, 56,  1, 19, 56,  1, 35, 57],
        [52, 43, 54, 45, 54,  1, 43, 55]])
targets:
torch.Size([4, 8])
tensor([[35, 19,  1, 37, 61,  1, 19, 45],
        [ 1, 43, 61, 45, 56,  0, 48, 54],
        [56,  1, 19, 56,  1, 35, 57, 19],
        [43, 54, 45, 54,  1, 43, 55, 37]])
----
when input is [54] the target: 35
when input is [54, 35] the target: 19
when input is [54, 35, 19] the target: 1
when input is [54, 35, 19, 1] the target: 37
when input is [54, 35, 19, 1, 37] the target: 61
when input is [54, 35, 19, 1, 37, 61] the target: 1
when input is [54, 35, 19, 1, 37, 61, 1] the target: 19
when input is [54, 35, 19, 1, 37, 61, 1, 19] the target: 45
when input is [54] the target: 1
when input is [54, 1] the target: 43
when input is [54, 1, 43] the target: 61
when input is [54, 1, 43, 61] the target: 45
when input is [54, 1, 43, 61, 45] the target: 56
when input is [54, 1, 

In [14]:
print(xb) # our input to the transformer

tensor([[54, 35, 19,  1, 37, 61,  1, 19],
        [54,  1, 43, 61, 45, 56,  0, 48],
        [45, 56,  1, 19, 56,  1, 35, 57],
        [52, 43, 54, 45, 54,  1, 43, 55]])


In [15]:
vocab_size

178699

In [16]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


torch.Size([32, 178699])
tensor(12.5640, grad_fn=<NllLossBackward0>)


KeyError: 149736